FROM python:3.9-slim
LABEL maintainer='Davi Lima'

ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install dependencies
RUN pip install redis==4.3.4 resend

# Copy worker script
COPY worker.py .

# Set the entrypoint to python
ENTRYPOINT ["python"]

# Default command
CMD ["worker.py"]
